name: docs

on:
    push:
        branches:
            - master

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 16.15.0
              uses: actions/setup-node@v3
              with:
                  node-version: 16.15.0

            - run: npm install
            - run: npm run test

            - name: Github Pages
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: docs
                  jekyll: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
